from __future__ import annotations

from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS_DIR = ROOT / "blog" / "posts"
OUTPUT = ROOT / "blog" / "_posts_index.md"


def _parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}

    lines = text.splitlines()
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break

    if end is None:
        return {}

    data: dict[str, str] = {}
    for line in lines[1:end]:
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value.startswith(("'", '"')) and value.endswith(("'", '"')):
            value = value[1:-1]
        data[key] = value
    return data


def _parse_date(value: str) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def _format_title(path: Path) -> str:
    return path.stem.replace("-", " ").title()


def build_index() -> None:
    posts = []
    for path in sorted(POSTS_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm = _parse_frontmatter(text)
        title = fm.get("title") or _format_title(path)
        date_str = fm.get("date", "")
        desc = fm.get("description", "")
        date_obj = _parse_date(date_str)
        rel_path = path.relative_to(ROOT).as_posix()
        posts.append((date_obj, date_str, title, desc, rel_path))

    posts.sort(key=lambda item: (item[0] or datetime.min), reverse=True)

    lines = [
        "<!-- This file is auto-generated by scripts/generate_blog_index.py. -->",
        "",
        "## Recent blog posts",
        "",
    ]

    if not posts:
        lines.append("No posts yet.")
    else:
        lines.extend([
            "| Title | Date | Excerpt |",
            "| --- | --- | --- |",
        ])
        for _, date_str, title, desc, rel_path in posts:
            link = f"[{title}]({rel_path})"
            lines.append(f"| {link} | {date_str} | {desc} |")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build_index()
